### ISSUE TITLE
no plugin.app or server.app found

### ISSUE THREAD

**Issue by farberm** [Ghawken/iMessagePlugin#6]
I can only add the Indigo 7.2 app not the plugin or server app. I did a search and they are not found. Where would I locate them?

**Comment by Ghawken** [comment]
Check the first thread with instructions

**Comment by Ghawken** [comment]
https://forums.indigodomo.com/viewtopic.php?f=297&t=21520

&

> /Library/Application Support/Perceptive Automation/Indigo 7 (or 7.2)
IndigoPluginHost.app
IndigoServer.app
Both located there to drag and drop into Security & Privacy Full Disk Access
